# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LWDA 2019
email: robert.jaeschke@hu-berlin.de
description: > # this means to ignore newlines until "baseurl:"
  Lernen. Wissen. Daten. Analysen. – Die LWDA 2019 an der Humboldt-Universität zu Berlin, 30.9.-2.10.2019.
baseurl: /ibi/lwda2019
url: https://pages.cms.hu-berlin.de
header: /images/uni.jpg

# theme: jekyll-theme-tactile
theme: slate

# Build settings
markdown: kramdown
